version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    container_name: 'app-docker'
    volumes:
      - .:/application
    ports:
      - "8081:8080"

  mysql:
    image: mysql:8.0.26
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5632:3306"

